version: '3.8'
services:
  db:
    image: postgres:12.2-alpine
    container_name: ${APP_NAME}-db
    networks:
      - backend
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5431:${DB_PORT} 
networks:
  backend:
    name: lambda-typescript-local-network
